Prefixed table names with replicache_
rocicorp/replicache-nextjs pull request #22
Opened 2022-11-04 18:46 UTC by nbarraud

I prefixed the `space`, `entry` and `client` tables with `replicache_` to avoid conflicts with existing userland tables.

2022-11-04 19:03 UTC, nbarraud commented
I haven't touched the version number but I would think the major should be bumped one since that's a breaking change.

2022-11-30 18:20 UTC, cesara requested changes
please fix failing test. In data.test.ts it should have the following expected output for the `createSpace` test

```
        expect(String(e)).contains(
          `duplicate key value violates unique constraint "replicache_space_pkey`
        );
```

2022-12-08 00:00 UTC, nbarraud commented
Rebased, made the test fix and also added the rimraf package for cross-OS compatibility (rm -rf) not available on Windows. Thank you!

2023-01-06 17:29 UTC, cesara approved these changes

2025-02-27 19:50 UTC, closed without merging